name: Tenebris CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest mypy black isort pycln flake8
        pip install -r requirements.txt

    - name: black
      run: black -l 120 --check tenebris/

    - name: isort
      run: isort tenebris/ --check-only

    - name: pycln
      run: pycln tenebris/

    - name: flake8
      run: flake8 tenebris/

    - name: mypy
      run: mypy tenebris/

