name: Tenebris CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest mypy black isort pycln flake8
        pip install -r requirements.txt

    - name: black
      run: black -l 120 --check .

    - name: isort
      run: isort --diff --check-only --settings-file pyproject.toml .

    - name: pycln
      run: pycln --diff --check --config pyproject.toml .

    - name: flake8
      run: flake8 .

    - name: mypy
      run: mypy --config-file ./pyproject.toml --install-types --non-interactive --namespace-packages --explicit-package-bases .
