name: Tenebris CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install project
      run: poetry install --no-interaction

    - name: Run black
      run: |
        source .venv/bin/activate
        black -l 120 --check .

    - name: Run isort
      run: |
        source .venv/bin/activate
        isort --diff --check-only --settings-file pyproject.toml .

    - name: Run pycln
      run: |
        source .venv/bin/activate
        pycln --diff --check --config pyproject.toml .

    - name: Run flake8
      run: |
        source .venv/bin/activate
        flake8 .

    - name: Run mypy
      run: |
        source .venv/bin/activate
        mypy --config-file ./pyproject.toml --install-types --non-interactive --namespace-packages --explicit-package-bases .
